# Generated by Django 5.2.4 on 2025-07-03 05:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500, verbose_name='URL nguồn')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL ảnh')),
                ('image_name', models.CharField(max_length=255, verbose_name='Tên ảnh')),
                ('local_path', models.CharField(blank=True, max_length=500, verbose_name='Đường dẫn local')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kích thước file')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Chiều rộng')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Chiều cao')),
                ('image_format', models.CharField(blank=True, max_length=10, verbose_name='Định dạng')),
                ('crawled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian crawl')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('downloading', 'Đang tải'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('error_message', models.TextField(blank=True, verbose_name='Thông báo lỗi')),
            ],
            options={
                'verbose_name': 'Ảnh đã crawl',
                'verbose_name_plural': 'Ảnh đã crawl',
                'ordering': ['-crawled_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=500, verbose_name='URL mục tiêu')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bắt đầu')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc')),
                ('total_images_found', models.PositiveIntegerField(default=0, verbose_name='Tổng ảnh tìm thấy')),
                ('images_downloaded', models.PositiveIntegerField(default=0, verbose_name='Ảnh đã tải')),
                ('images_failed', models.PositiveIntegerField(default=0, verbose_name='Ảnh thất bại')),
                ('status', models.CharField(choices=[('running', 'Đang chạy'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy')], default='running', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Phiên crawl',
                'verbose_name_plural': 'Phiên crawl',
                'ordering': ['-started_at'],
            },
        ),
    ]
