# Generated by Django 5.2.4 on 2025-07-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_crawler', '0001_initial'),
    ]

    operations = [
    ]
